sudo: false
language: java
jdk:
- oraclejdk8
before_install: git clone --depth 1 https://github.com/igniterealtime/ci-tooling.git
  target/ci-tooling
deploy:
  provider: script
  script: mvn deploy --settings target/ci-tooling/maven-settings-for-openfire-plugins.xml
  skip_cleanup: true
  on:
    all_branches: true
env:
  global:
  - secure: f0JCBvGIHTfj5UqARLg+Va648ot+KlkglHAoZ1rWusHGeO26iwgFlMZVsFbbiTb0t2ARD7naIboKg1pcJWdEjerUAeua4E4F5zMPvtUcf6VB2y6c6gtIoOifn/LntTcja3SoT2dVXh3uH4m0upV/LuJLrPGcAt9e5FwwwL5ge4ZxHULOavCCd5h3JIsGEzGLx7RlHfzPiZse3xZyZPteW8xc2ly7lbqlYJPpdWv2z0V40LHNUIjqjgV+CsNjVerorF0Z95dlubhiwkO5qhMFIicl31fj/YjHfJ9J82kwu8AKtuVTkHylVo0Q5LtB6NK2LewxMP+DwS3X4LNeb/tkb3xpZxF2kpWx42YA2JWfIGvTsJWw4tdekci7fmZdIsz7Fj1rbLXgfkBGcvKveEBfUPtuhSbJnpsWukpki7pdd2sOuYwSfzS8aOFT49HuZlqKYVLt3o6QLcwHIUU5vbHqDvTNoLTk6Cdx3OaoEGAFtipDxJGXqxgxMZuIO/Yg2NVpm6S3GzBxOT9EVac3IJTKURERvn0FvysR2TyHv3IOMugG60lm/ybYca5hVe7JxDPeaBWtgpp8fmhJRTQs/OUdFsmRH3q9JtRlEdK1T2NySh5G0nFAJDXWBS7AiJsHxg2BvyCDWcVFu9a/Eq+jj/ll8WPCOTYMgArQ+6jX4XrrECA=
  - secure: Ea8kUKlAalLekUGKtVYGjT9c5vr406pUiH976dH6DTz6ijNV1vkXJffB3l7Wq35iIo9IdoA5/HNGpg+rE1vRmDVoaoJW7XI1y7ypiBhdKqQNWcIuHP6cvTtSRDIMjg7YDh4qvjMWjwG6jS3W3/f/WvUZ+wpNzSpPAK/Kq69f1XUtbOq1GEC3VbAw3eGJioc8210fKlpj+fEEJSGLfR9RX6hb05X1z4hyhaB9mGwtRqyJ4Az6DPlE91J1+dUKMDh5RVcOTewQKey1qx43GsJwP3yEiBQFGUCz50eREJC61jb3+WUEz8BE3zEXQ9l/wBTT4U2YkniECep857tkAHmm0Vbed3teerA9hqvY4hLDNWi/x7rIsSpkhNkHA7NJa8T8qVfBvtUnh5g4JhZYGqA7msBuzdI82FkdV2i/7xHHGAq+OlHWVbhavjZVfQN6gflb7YKtZyy17omCzZFPwjD2JpkhkRk2cH921uke3YgqfyaEsA5V4IHh+frF2jIRAcBfcfYY7q1SZnsVreIUEdCRfurqWBatn3w223mEES8VSSQv1ESWe9MSjvGNPmX4enMVdE8aUokOEMkyrdT118wkrYGuyv/iWxYT3T8cmmHFsiP+SAqE5IA644XFs/LFCFDdENO08f7ggX+3qiRoODyZZoNJxLuMhr6hg/LsuiO0gp8=
